articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('creates2/', views.create2, name='create2'),

    path('<int:id>/', views.detail, name='detail'),

    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
]

modelform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    # model = Article 이렇게 하지 않은 이유?
    # 변수에 넣는 것은 어트리뷰트 - 여기에 forms.CharField 와 같은 것들을 넣는것이 올바르지 않다
    class Meta:
        model = Article
        fields = '__all__'

        

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm

# Create your views here.
def index(request):
    articles = Article.objects.all()

    context = {
        'articles': articles
    }

    return render(request, 'articles/index.html', context)

def create(request):
    # method = 어떤 방식으로 들어왔는지
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')

        article = Article(title=title, content=content)
        article.save()

        return redirect('articles:index')
    
    else:
        return render(request, 'articles/create.html')
    

def create2(request):
    # 경우의수
    # 1. GET 요청이 들어온경우 : Form 만들어서 html 문서 사용자에게 전송
    # 2. POST 요청이 들어온 경우 : 데이터 검증에 실패했을 때(검증된 데이터는 그대로 보여줘야함)
    # 3. POST 요청이 들어온 경우 : 데이터 검증에 성공했을 때()

    # 5) POST 요청이 들어온 경우(데이터가 잘못된 경우)
    # 10) POST 요청이 들어온 경우(데이터가 잘 들어온 경우)
    if request.method == 'POST':
        # 6) Form에 사용자가 입력한 정보(X)를 담아서
        # 11) Form에 사용자가 입력한 정보(o)를 담아서
        form = ArticleForm(request.POST)
        # 3번
        # 7) 검증단계 실패
        # 12) 검증단계 성공
        if form.is_valid():
            # 13) form을 저장하고 저장한 데이터를 article 변수에 담기
            article = form.save()
            # 14) 방금 생성된 article detail 페이지로 redirect
            return redirect('articles:detail', id=article.id)
        # # 2번
        # else:
        #     context = {
        #         'form': form,
        #     }
        #     return render(request, 'articles/form.html', context)
    # 1) GET 요청이 들어온 경우
    else:
        # 2) 비어있는 Form 만들어서
        form = ArticleForm()
    # 3) context dict에 담고
    # 8) 검증 실패한 Form을 context dict에 담고
    context = {
        'form': form,
    }
    # 4) form.html을 랜더링
    # 9) form.html을 랜더링
    return render(request, 'articles/form.html', context)



def detail(request, id):
    article = Article.objects.get(id=id)

    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)

def update(request, id):
    article = Article.objects.get(id=id)

    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.id)
    else:
        form = ArticleForm(instance=article)

    context = {
        'form': form,
    }    

    return render(request, 'articles/form.html', context)

def delete(request, id):
    article = Article.objects.get(id=id)
    article.delete() 
    return redirect('articles:index')

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
    <h1>create</h1>
    
    <form action="" method="POST">
        {% csrf_token %}
        <input type="text" name="title">
        <textarea name="content" id="" cols="30" rows="10"></textarea>
        <input type='submit'>
    </form>
{% endblock %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{article.title}}</h1>
<p>{{article.content}}</p>

<p>{{article.created_at}}</p>
<p>{{article.updated_at}}</p>

<a href="{% url 'articles:update' id=article.id %}">update</a>
<a href="{% url 'articles:delete' id=article.id %}">delete</a>

{% endblock %}

articles/templates/articles/form.html
{% extends 'base.html' %}


{% block content %}

{% if request.resolver_match.url_name == 'create2' %}
    <h1>create(form)</h1>
{% else %}
    <h1>update(form)</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>

{% endblock %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
<h1>index</h1>

{% for article in articles %}
    <h3>{{article.title}}</h3>
    <a href="{% url 'articles:detail' id=article.id %}">detail</a>
    <hr>

{% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'articles:index' %}">home</a>
    <a href="/articles/create/">create</a>
    <a href="{% url 'articles:create2' %}">create2(form)</a>
    {% block content %}
    
    {% endblock %}
</body>
</html>